version: '3'

services:
  #nginx:
  #  image: nginx:1.15-alpine
  #  ports:
  #    - "80:80"
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #    # - /etc/letsencrypt:/etc/letsencrypt
  #  depends_on:
  #    - authentication_app
  #    - products_api
  #    - purchase_api
  #  networks:
  #    - fastpay

  authentication_app:
    image: registry.gitlab.com/fastpay-pi2/authentication-api/app:latest
    depends_on:
      - authentication_db
    networks:
      - fastpay
      - auth
    ports:
      - '3001:3001'

  authentication_db:
    image: mongo
    networks:
      - auth
    ports:
      - 27017:27017

  products_api:
    image: registry.gitlab.com/fastpay-pi2/products-api/app:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
      - POSTGRES_HOST=products_db
      - POSTGRES_PORT=5432
      - PRODUCT_API_URL=http://products_api:3000
    depends_on:
      - products_db
    networks:
      - fastpay
      - products
    ports:
      - "3000:3000"

  products_db:
    image: registry.gitlab.com/fastpay-pi2/products-api/db:latest
    networks:
      - products
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=db
      - POSTGRES_HOST=products_db
      - POSTGRES_PORT=5432
      - PRODUCT_API_URL=http://products_api:3000
    ports:
      - "5432:5432"

  purchase_api:
    image: registry.gitlab.com/fastpay-pi2/purchase-api/app:latest
    networks:
      - fastpay
      - purchase
    ports:
      - 5000:5000
    depends_on:
      - purchase_db
    environment:
      - DB_NAME=purchase
      - DB_URL=mongodb://purchase_db:27018/purchase
      - DB_TEST_NAME=purchase_test
      - DB_TEST_URL=mongodb://purchase_db:27018/purchase_test
      - FLASK_APP=application/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=application.config.DevelopmentConfig
      - PRODUCTS_API=http://products_api:3000/
  
  purchase_db:
    image: mongo
    command: mongod --port 27018
    volumes:
      - /mongo_purchase:/data/db
    networks:
      - purchase
    ports:
      - 27018:27018

  data-visualization:
    image: registry.gitlab.com/fastpay-pi2/data-visualization/script 
    container_name: data_visualization
    networks:
      - fastpay
    depends_on:
      - elasticsearch
    environment:
      - PURCHASE_API=http://purchase_api:5000/
      - PRODUCTS_API=http://products_api:3000/
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  elasticsearch:
    container_name: elasticsearch
    image: registry.gitlab.com/fastpay-pi2/data-visualization/elasticsearch 
    # restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - esbackup:/usr/share/elasticsearch/backup
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
    networks:
      - fastpay

  kibana:
    container_name: kibana
    image: registry.gitlab.com/fastpay-pi2/data-visualization/kibana 
    # restart: unless-stopped
    ports:
      - 5601:5601
    environment:
      - SERVER_PORT=5601
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - KIBANA_URL=http://kibana:5601
    depends_on:
      - elasticsearch
    networks:
      - fastpay

networks:
  fastpay:
  auth:
  products:
  purchase:

volumes:
  esbackup:
  esdata:
    driver: local
